/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
args.world_size=16, args.num_gpus=[2, 2, 2, 2]
Traceback (most recent call last):
  File "pretrain_gpt.py", line 135, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step_func,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/training.py", line 113, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/initialize.py", line 59, in initialize_megatron
    set_global_variables(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 91, in set_global_variables
    args = _parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/global_vars.py", line 107, in _parse_args
    _GLOBAL_ARGS = parse_args(extra_args_provider=extra_args_provider,
  File "/home/zhanda/workspace/Dazzle/benchmark/superscaler/SuperScaler/runtime/megatron/arguments.py", line 127, in parse_args
    assert args.world_size == sum(args.num_gpus), \
AssertionError: number of GPUs should be equal to sum(mp_size * dp_size)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 731) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretrain_gpt.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 732)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 733)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 734)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 735)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 738)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 742)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-30_23:14:47
  host      : ip-172-31-3-214.us-east-2.compute.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 731)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
